version: '3.5'
services:
  location:
    image: postgres:latest
    container_name: location
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5460:5432"


volumes:
  postgres-db:
    driver: local